version: '3.8'

services:
  app:
    build:
      dockerfile: .docker/dev/app/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    links:
      - postgres
      - postgres-testing
      - redis
      - mailhog
    hostname: api
    ports:
      - "8000:8000"
    networks:
      - api
      - gateway
    restart: unless-stopped

  queue:
    build:
      dockerfile: .docker/dev/queue/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    links:
      - postgres
      - redis
      - mailhog
    networks:
      - api

  schedule:
    build:
      dockerfile: .docker/dev/schedule/Dockerfile
      args:
        IMAGE_REGISTRY: ${IMAGE_REGISTRY}
        IMAGE_TAG: ${IMAGE_TAG}
    volumes:
      - ./:/var/www/html
    links:
      - postgres
      - redis
      - mailhog
    networks:
      - api

  # postgres:
  #   build:
  #     dockerfile: .docker/dev/postgres/Dockerfile
  #   environment:
  #     POSTGRES_DB: ${DB_DATABASE}
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #     - ./.docker/dev/postgres/dumps/:/tmp
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - api

  mariadb:
    build:
      dockerfile: .docker/dev/mariadb/Dockerfile
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: laravel
      TEST_DB_NAME: laravel_test
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks: 
      - api

  postgres-testing:
    build:
      dockerfile: .docker/dev/postgres/Dockerfile
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - api

  redis:
    build:
      dockerfile: .docker/dev/redis/Dockerfile
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - api

  mailhog:
    build:
      dockerfile: .docker/dev/mailhog/Dockerfile
    ports:
      - "8025:8025"
    networks:
      - api

volumes:
  postgres:
    driver: local

  redis:
    driver: local

networks:
  api:
    name: api

  gateway:
    name: gateway
    external: true
